/**
 *
 *  MenusConfig.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

using namespace drogon::orm;
namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace sqlite3 
{

class MenusConfig
{
  public:
    struct Cols
    {
        static const std::string _id;
        static const std::string _first_course_1_id;
        static const std::string _first_course_2_id;
        static const std::string _first_course_3_id;
        static const std::string _first_course_4_id;
        static const std::string _first_course_5_id;
        static const std::string _second_course_1_id;
        static const std::string _second_course_2_id;
        static const std::string _second_course_3_id;
        static const std::string _second_course_4_id;
        static const std::string _second_course_5_id;
    };

    const static int primaryKeyNumber;
    const static std::string tableName;
    const static bool hasPrimaryKey;
    const static std::string primaryKeyName;
    using PrimaryKeyType = uint64_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names, 
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all 
     * columns by an asterisk), please set the offset to -1.
     */
    explicit MenusConfig(const Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit MenusConfig(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    MenusConfig(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    MenusConfig() = default;
    
    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson, 
                          std::string &err, 
                          bool isForCreation);

    /**  For column id  */
    ///Get the value of the column id, returns the default value if the column is null
    const uint64_t &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint64_t> &getId() const noexcept;

    /**  For column first_course_1_id  */
    ///Get the value of the column first_course_1_id, returns the default value if the column is null
    const uint64_t &getValueOfFirstCourse1Id() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint64_t> &getFirstCourse1Id() const noexcept;
    ///Set the value of the column first_course_1_id
    void setFirstCourse1Id(const uint64_t &pFirstCourse1Id) noexcept;
    void setFirstCourse1IdToNull() noexcept;

    /**  For column first_course_2_id  */
    ///Get the value of the column first_course_2_id, returns the default value if the column is null
    const uint64_t &getValueOfFirstCourse2Id() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint64_t> &getFirstCourse2Id() const noexcept;
    ///Set the value of the column first_course_2_id
    void setFirstCourse2Id(const uint64_t &pFirstCourse2Id) noexcept;
    void setFirstCourse2IdToNull() noexcept;

    /**  For column first_course_3_id  */
    ///Get the value of the column first_course_3_id, returns the default value if the column is null
    const uint64_t &getValueOfFirstCourse3Id() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint64_t> &getFirstCourse3Id() const noexcept;
    ///Set the value of the column first_course_3_id
    void setFirstCourse3Id(const uint64_t &pFirstCourse3Id) noexcept;
    void setFirstCourse3IdToNull() noexcept;

    /**  For column first_course_4_id  */
    ///Get the value of the column first_course_4_id, returns the default value if the column is null
    const uint64_t &getValueOfFirstCourse4Id() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint64_t> &getFirstCourse4Id() const noexcept;
    ///Set the value of the column first_course_4_id
    void setFirstCourse4Id(const uint64_t &pFirstCourse4Id) noexcept;
    void setFirstCourse4IdToNull() noexcept;

    /**  For column first_course_5_id  */
    ///Get the value of the column first_course_5_id, returns the default value if the column is null
    const uint64_t &getValueOfFirstCourse5Id() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint64_t> &getFirstCourse5Id() const noexcept;
    ///Set the value of the column first_course_5_id
    void setFirstCourse5Id(const uint64_t &pFirstCourse5Id) noexcept;
    void setFirstCourse5IdToNull() noexcept;

    /**  For column second_course_1_id  */
    ///Get the value of the column second_course_1_id, returns the default value if the column is null
    const uint64_t &getValueOfSecondCourse1Id() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint64_t> &getSecondCourse1Id() const noexcept;
    ///Set the value of the column second_course_1_id
    void setSecondCourse1Id(const uint64_t &pSecondCourse1Id) noexcept;
    void setSecondCourse1IdToNull() noexcept;

    /**  For column second_course_2_id  */
    ///Get the value of the column second_course_2_id, returns the default value if the column is null
    const uint64_t &getValueOfSecondCourse2Id() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint64_t> &getSecondCourse2Id() const noexcept;
    ///Set the value of the column second_course_2_id
    void setSecondCourse2Id(const uint64_t &pSecondCourse2Id) noexcept;
    void setSecondCourse2IdToNull() noexcept;

    /**  For column second_course_3_id  */
    ///Get the value of the column second_course_3_id, returns the default value if the column is null
    const uint64_t &getValueOfSecondCourse3Id() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint64_t> &getSecondCourse3Id() const noexcept;
    ///Set the value of the column second_course_3_id
    void setSecondCourse3Id(const uint64_t &pSecondCourse3Id) noexcept;
    void setSecondCourse3IdToNull() noexcept;

    /**  For column second_course_4_id  */
    ///Get the value of the column second_course_4_id, returns the default value if the column is null
    const uint64_t &getValueOfSecondCourse4Id() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint64_t> &getSecondCourse4Id() const noexcept;
    ///Set the value of the column second_course_4_id
    void setSecondCourse4Id(const uint64_t &pSecondCourse4Id) noexcept;
    void setSecondCourse4IdToNull() noexcept;

    /**  For column second_course_5_id  */
    ///Get the value of the column second_course_5_id, returns the default value if the column is null
    const uint64_t &getValueOfSecondCourse5Id() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint64_t> &getSecondCourse5Id() const noexcept;
    ///Set the value of the column second_course_5_id
    void setSecondCourse5Id(const uint64_t &pSecondCourse5Id) noexcept;
    void setSecondCourse5IdToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 11;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend Mapper<MenusConfig>;
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<uint64_t> id_;
    std::shared_ptr<uint64_t> firstCourse1Id_;
    std::shared_ptr<uint64_t> firstCourse2Id_;
    std::shared_ptr<uint64_t> firstCourse3Id_;
    std::shared_ptr<uint64_t> firstCourse4Id_;
    std::shared_ptr<uint64_t> firstCourse5Id_;
    std::shared_ptr<uint64_t> secondCourse1Id_;
    std::shared_ptr<uint64_t> secondCourse2Id_;
    std::shared_ptr<uint64_t> secondCourse3Id_;
    std::shared_ptr<uint64_t> secondCourse4Id_;
    std::shared_ptr<uint64_t> secondCourse5Id_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[11]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id = ?";
        return sql;                   
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id = ?";
        return sql;                   
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        if(dirtyFlag_[1])
        {
            sql += "first_course_1_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "first_course_2_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "first_course_3_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "first_course_4_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "first_course_5_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "second_course_1_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[7])
        {
            sql += "second_course_2_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[8])
        {
            sql += "second_course_3_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[9])
        {
            sql += "second_course_4_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[10])
        {
            sql += "second_course_5_id,";
            ++parametersCount;
        }
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";
        
        if(dirtyFlag_[1])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[2])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[3])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[4])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[5])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[6])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[7])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[8])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[9])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[10])
        {
            sql.append("?,");

        } 
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        sql.append(1, ')');
        LOG_TRACE << sql;
        return sql;   
    }
};
} // namespace sqlite3
} // namespace drogon_model
